#!/usr/bin/env bash
# vim:foldmethod=marker

# Variables {{{

LUNARIS_MOTION_CACHE_FILE="$HOME/.cache/lunaris-motion"
LUNARIS_MOTION_CONFIG_FILE="$HOME/.config/lunaris/motion.sh"
LUNARIS_MOTION_SOCKET_FILE="/run/user/$UID/lunaris-motion.sock"
LUNARIS_MOTION_SYSTEM_DIR="/etc/lunaris/motion"
# }}}

# Functions {{{

# Log {{{

log() {
	echo "[$(date +'%Y-%m-%d %H:%M:%S')]: $*" >&2
}
# }}}

# Configuration {{{

user_config() {
	if [[ -f "$LUNARIS_MOTION_CONFIG_FILE" ]]; then
		# shellcheck disable=SC1090
		source "$LUNARIS_MOTION_CONFIG_FILE"
		log "[INFO]: Using user configuration"
	fi
}
# }}}

# Workshop {{{

workshop() {
	local selected_workshop_file workshop_dir

	# Check for workshop directory
	if [[ -d "$LUNARIS_MOTION_CONFIG_WORKSHOP_DIR" ]]; then
		workshop_dir="$LUNARIS_MOTION_CONFIG_WORKSHOP_DIR"
	elif [[ -d "$HOME/.local/share/Steam/steamapps/workshop/content/431960" ]]; then
		workshop_dir="$HOME/.local/share/Steam/steamapps/workshop/content/431960"
	elif [[ -d "$HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/workshop/content/431960" ]]; then
		workshop_dir="$HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/workshop/content/431960"
	else
		log "[ERROR]: Workshop directory is missing"
		exit 1
	fi

	# Select Wallpaper
	selected_workshop_file="$(rofi -no-config -normal-window -show-icons -theme "$LUNARIS_MOTION_SYSTEM_DIR/lunaris-motion-grid" \
		-show recursivebrowser -recursivebrowser-directory "$workshop_dir" -recursivebrowser-filter-regex "(.*\.json|.*\.gif|.*\.jpg|.*\.png)" -recursivebrowser-command "printf '%s\n'" 2>/dev/null)"

	# Exit safeguard
	[[ -z "$selected_workshop_file" ]] && exit 0

	# Save selection on cache
	printf '%s\n' "LUNARIS_MOTION_FILE=\"$selected_workshop_file\"" >"$LUNARIS_MOTION_CACHE_FILE"
}
# }}}

# Local {{{

local_video() {
	local selected_video_file video_dir

	# Check for video directory
	if [[ -d "$LUNARIS_MOTION_CONFIG_VIDEO_DIR" ]]; then
		video_dir="$LUNARIS_MOTION_CONFIG_VIDEO_DIR"
	elif [[ -d "$(xdg-user-dir VIDEOS)/lunaris-motion" ]]; then
		video_dir="$(xdg-user-dir VIDEOS)/lunaris-motion"
	elif [[ -d "$HOME/Videos/lunaris-motion" ]]; then
		video_dir="$HOME/Videos/lunaris-motion"
	else
		log "[ERROR]: Video directory is missing"
		exit 1
	fi

	# Select Wallpaper
	selected_video_file="$(rofi -no-config -normal-window -show-icons -theme "$LUNARIS_MOTION_SYSTEM_DIR/lunaris-motion-list" \
		-show filebrowser -filebrowser-directory "$video_dir" -filebrowser-sorting-method "name" -filebrowser-directories-first true -filebrowser-show-hidden true -filebrowser-command "printf '%s\n'" 2>/dev/null)"

	# Exit safeguard
	[[ -z "$selected_video_file" ]] && exit 0

	# Save selection on cache
	printf '%s\n' "LUNARIS_MOTION_FILE=\"$selected_video_file\"" >"$LUNARIS_MOTION_CACHE_FILE"
}
# }}}

# Player {{{

player() {
	local player_config

	# Source cached selection
	if [[ -f "$LUNARIS_MOTION_CACHE_FILE" ]]; then
		# shellcheck disable=SC1090
		source "$LUNARIS_MOTION_CACHE_FILE"
	else
		log "[ERROR]: Cached selection is missing "
		exit 1
	fi

	# Check for mpv config
	if [[ -f "$LUNARIS_MOTION_CONFIG_PLAYER/mpv.conf" ]]; then
		player_config="$LUNARIS_MOTION_CONFIG_PLAYER"
	elif [[ -f "$LUNARIS_MOTION_SYSTEM_DIR/mpv/mpv.conf" ]]; then
		player_config="$LUNARIS_MOTION_SYSTEM_DIR/mpv"
	else
		log "[ERROR]: Mpv configuration is missing"
	fi

	# Check for existing video file
	if [[ ! -f "$LUNARIS_MOTION_FILE" ]]; then
		log "[ERROR]: Video selected is missing"
	fi

	# Change video on existing player
	if pgrep xwinwrap --quiet && [[ -S "$LUNARIS_MOTION_SOCKET_FILE" ]]; then
		printf '{"command": ["loadfile", "%s", "replace"]}\n' "$LUNARIS_MOTION_FILE" | socat - UNIX-CONNECT:"$LUNARIS_MOTION_SOCKET_FILE" >/dev/null
	else
		# Kill old instances
		cleanup

		# Start new player
		xwinwrap -b -d -fdt -fs -nf -ovr -s -sp -st -- \
			mpv -wid WID "$LUNARIS_MOTION_FILE" --config-dir="$player_config" --input-ipc-server="$LUNARIS_MOTION_SOCKET_FILE" --script="$LUNARIS_MOTION_SYSTEM_DIR/mpv/lunaris-motion.lua" \
			--fullscreen --panscan=1 --no-audio --loop \
			--input-default-bindings=no --osc=no --osd-level=0 --terminal=no 2>/dev/null
	fi
}

cleanup() {
	pkill xwinwrap
	pkill -f "$LUNARIS_MOTION_SYSTEM_DIR/lunaris-motion-daemon.sh"
	rm -f "$LUNARIS_MOTION_SOCKET_FILE"
}
# }}}

# Socket {{{

player_play() {
	printf '%s\n' '{ "command": ["set_property", "pause", false] }' | socat - UNIX-CONNECT:"$LUNARIS_MOTION_SOCKET_FILE" >/dev/null
}

player_pause() {
	printf '%s\n' '{ "command": ["set_property", "pause", true] }' | socat - UNIX-CONNECT:"$LUNARIS_MOTION_SOCKET_FILE" >/dev/null
}
# }}}

# Slave {{{

daemon() {
	# Start daemon
	nohup "$LUNARIS_MOTION_SYSTEM_DIR/lunaris-motion-daemon.sh" >/dev/null 2>&1 &
}
# }}}

# Menu {{{

menu() {
	local rofi_menu

	# Display menu
	rofi_menu="$(printf '󰓓 Workshop\n󰈫 Video\n󰦛 Restore\n󱨘 Daemonless\n󰐌 Play\n󰏥 Pause\n󰰱 Kill' | rofi -dmenu -sync -i -p ' Lunaris-Motion:')"

	case "$rofi_menu" in
	"󰓓 Workshop")
		user_config
		workshop
		player
		daemon
		;;

	"󰈫 Video")
		user_config
		local_video
		player
		daemon
		;;

	"󰦛 Restore")
		user_config
		cleanup
		player
		daemon
		;;

	"󱨘 Daemonless")
		user_config
		cleanup
		player
		;;

	"󰐌 Play")
		player_play
		;;

	"󰏥 Pause")
		player_pause
		;;

	"󰰱 Kill")
		cleanup
		;;
	esac
}
# }}}

# Help {{{

show_help() {
	cat <<EOF
USAGE:
	lunaris-motion <command>

COMMANDS:
  -w|--workshop     Select video from workshop
  -v|--video        Select video from local directory
  -r|--restore      Restore cached wallpaper with daemon
  -d|--daemonless		Restore cached wallpaper without daemon

  --play            Resume player
  --pause           Pause player
  -k|--kill  				Kill player


  -h|--help         Display this help message

EOF
}
# }}}

# }}}

# Master {{{

case "$1" in
-w | --workshop)
	user_config
	workshop
	player
	daemon
	;;

-v | --video)
	user_config
	local_video
	player
	daemon
	;;

-r | --restore)
	user_config
	cleanup
	player
	daemon
	;;

-d | --daemonless)
	user_config
	cleanup
	player
	;;

--play)
	player_play
	;;

--pause)
	player_pause
	;;

-k | --kill)
	cleanup
	;;

-m | --menu)
	menu
	;;

-h | --help)
	show_help
	exit 0
	;;

*)
	log "[ERROR]: Option not found, use -h or --help for help"
	exit 1
	;;
esac
# }}}
