#!/usr/bin/env bash
# vim:foldmethod=marker

# Variables {{{

# Settings {{{

LUNARIS_MOTION_PLAYER_CONFIG=""
LUNARIS_MOTION_WALLPAPER_ENGINE_DIR=""
# }}}

# Default {{{

LUNARIS_MOTION_CACHE_FILE="${XDG_CACHE_HOME:-${HOME}/.cache}/lunaris-motion"
LUNARIS_MOTION_SYSTEM_DIR="${XDG_CONFIG_DIRS:-/etc/xdg}/lunaris-motion"
# }}}

# }}}

# Functions {{{

# Log {{{

log() {
  echo "[$(date +'%Y-%m-%d %H:%M:%S')]: $*" >&2
}
# }}}

# Wallpaper Engine {{{

wallpaper_engine() {

  # Check for system Steam
  if [[ -d "$HOME/.local/share/Steam/steamapps/workshop/content/431960"  ]]; then
    wallpaper_engine_dir="$HOME/.local/share/Steam/steamapps/workshop/content/431960"

  # Check for flatpak Steam
  elif [[ -d "$HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/workshop/content/431960" ]]; then
    wallpaper_engine_dir="$HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/workshop/content/431960"

  # Check for custom Steam
  elif [[ -d "$LUNARIS_MOTION_WALLPAPER_ENGINE_DIR" ]]; then
    wallpaper_engine_dir="$LUNARIS_MOTION_WALLPAPER_ENGINE_DIR"
  
  # Exit if Wallpaper Engine is not found
  else
    log "[ERROR]: No Wallpaper Engine installation found"
    exit 1
  fi

  # Select Wallpaper
  selected_wallpaper="$(rofi -config "$LUNARIS_MOTION_SYSTEM_DIR/lunaris-motion-grid" -show recursivebrowser -normal-window \
    -recursivebrowser-directory "$wallpaper_engine_dir" -recursivebrowser-filter-regex "(.*\.json|.*\.gif|.*\.jpg|.*\.png)" 2>/dev/null)"

  # Exit if no wallpaper is selected
  if [[ -z "$selected_wallpaper" ]]; then
    log "[ERROR]: No selected wallpaper"
    exit 1
  else
    # Set wallpaper on LUNARIS_MOTION_CACHE_FILE
    printf '%s' "$selected_wallpaper" > "$LUNARIS_MOTION_CACHE_FILE"
  fi
}
# }}}

# Player {{{

player() {

  # Kill old instances
  if [[ "$(pgrep xwinwrap 2>/dev/null)" ]]; then
    pkill xwinwrap
    log "[INFO]: Killed old instances"
  fi

  # Load wallpaper from LUNARIS_MOTION_CACHE_FILE
  if [[ -f "$LUNARIS_MOTION_CACHE_FILE" ]]; then
    wallpaper_file="$(<"$LUNARIS_MOTION_CACHE_FILE")"
    log "[INFO]: Last video loaded from cache"
  else
    log "[ERROR]: No wallpaper loaded"
    exit 1
  fi

  # Load player configuration
  if [[ -f "$LUNARIS_MOTION_PLAYER_CONFIG/mpv.conf" ]]; then
    player_config="$LUNARIS_MOTION_PLAYER_CONFIG"
    log "[INFO]: User player configuration loaded"
  else
    player_config="$LUNARIS_MOTION_SYSTEM_DIR"
    log "[INFO]: System player configuration loaded"
  fi

  # Embed video
  xwinwrap -ni -fdt -fs -s -st -sp -b -nf -ovr -d -- \
    mpv -wid WID "$wallpaper_file" --config-dir="$player_config" \
    --fullscreen --panscan=1 --no-audio --loop \
    --input-default-bindings=no --input-cursor=no --osc=no --osd-level=0 --terminal=no 2>/dev/null
}
# }}}

# }}}

wallpaper_engine
player